language: python

python:
  - "2.7"

sudo: false

before_install:
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda create -q -y -n teetool-env python=$TRAVIS_PYTHON_VERSION numpy mayavi matplotlib
  - source activate teetool-env
  - which pip
  - pip install pathos
  - python setup.py install

before_script:
  - conda list
  - python setup.py install

script:
  - py.test
