language: python
python:
  - "2.7"

sudo: true

before_install:
  - sudo apt-get install python-vtk

install:
  - pip install -r requirements.txt

script:
  - py.test -v

notifications:
  email:
    on_failure: always
