language: python

python:
  - "2.7"

sudo: false

before_install:
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

install:
  - conda create -q -y -n teetool-env python=2.7 --file requirements_conda.txt
  - source activate teetool-env
  - pip install --requirement requirements_pip.txt

before_script:
  - conda list
  - python setup.py install
  - export PYTHONPATH="$TRAVIS_BUILD_DIR:$PYTHONPATH"

script:
  - echo $PATH
  - python --version
  - which py.test
  - which python
  - echo $PWD
  - ls
  - ls test
  - py.test . -v

notifications:
  email:
    on_failure: always
